---
region: 'eu-west-2'

component: 'bastion'
deployment_identifier: "%{hiera('seed')}"

domain_name: 'infrablocks.click'

allowed_cidrs:
  - '0.0.0.0/0'
egress_cidrs:
  - '10.0.0.0/8'
  - '192.168.0.0/16'

ami: 'ami-bb373ddf'
instance_user: 'centos'
instance_type: 't2.medium'
ssh_public_key_path: "%{cwd}/config/secrets/bastion/ssh.public"
ssh_private_key_path: "%{cwd}/config/secrets/bastion/ssh.private"

minimum_instances: 1
maximum_instances: 1
desired_instances: 1

vpc_cidr: '10.1.0.0/16'
availability_zones:
  - "eu-west-2a"
  - "eu-west-2b"

public_zone_id: 'Z08829023L5IPIQBJOX63'
private_zone_id: 'Z0211739BXR21FNN139O'

listeners:
  - lb_port: 22
    lb_protocol: "TCP"
    instance_port: 22
    instance_protocol: "TCP"
    ssl_certificate_id: ""

access_control:
  - lb_port: 22
    instance_port: 22
    allow_cidrs:
      - "0.0.0.0/0"

health_check_target: 'TCP:22'

include_public_dns_record: "yes"
include_private_dns_record: "yes"

expose_to_public_internet: "yes"
