---
configuration_directory: "%{cwd}/examples/full"
state_file: "%{cwd}/state/full.tfstate"
vars:
  region: "%{hiera('region')}"

  vpc_cidr: "%{hiera('vpc_cidr')}"
  availability_zones: "%{hiera('availability_zones')}"

  component: "%{hiera('component')}"
  deployment_identifier: "%{hiera('deployment_identifier')}"

  domain_name: "%{hiera('domain_name')}"
  public_zone_id: "%{hiera('public_zone_id')}"
  private_zone_id: "%{hiera('private_zone_id')}"

  listeners: "%{hiera('listeners')}"

  access_control: "%{hiera('access_control')}"

  health_check_target: "%{hiera('health_check_target')}"

  include_public_dns_record: "%{hiera('include_public_dns_record')}"
  include_private_dns_record: "%{hiera('include_private_dns_record')}"

  expose_to_public_internet: "%{hiera('expose_to_public_internet')}"

  ssh_public_key_path: "%{hiera('ssh_public_key_path')}"

  allowed_cidrs: "%{hiera('allowed_cidrs')}"
  egress_cidrs: "%{hiera('egress_cidrs')}"
